postgres:
  enabled: true
  replicaCount: 1
  image: "postgres:13"
  imagePullPolicy: IfNotPresent
  username: "palmruser"
  password: "yourpassword"
  db: "palmrdb"
  persistence:
    size: "5Gi"

# To use the recommended MinIO storage, set enabled: true.
# To use local storage (for example, backed by Longhorn), set enabled: false.
minio:
  enabled: true
  replicaCount: 1
  image: "minio/minio:latest"
  imagePullPolicy: IfNotPresent
  rootUser: "minioadmin"
  rootPassword: "minioadminpassword"
  persistence:
    size: "10Gi"

palmr:
  enabled: true
  replicaCount: 1
  image: "kyantech/palmr:latest"
  imagePullPolicy: IfNotPresent
  storage:
    # When true, Palmr will expect MinIO to be deployed.
    # When false, Palmr uses a dedicated PVC for direct (e.g. Longhorn) storage.
    useMinio: true
    pvc:
      enabled: true
      size: "10Gi"
      # Set this to the storage class you want to use (e.g. "longhorn")
      storageClassName: "longhorn"
