postgres:
  enabled: true
  replicaCount: 1
  image: "postgres:13"
  imagePullPolicy: IfNotPresent
  username: "palmruser"
  password: "yourpassword"
  db: "palmrdb"
  persistence:
    size: "5Gi"

minio:
  enabled: true    # Set to false to disable MinIO and use local storage instead.
  replicaCount: 1
  image: "minio/minio:latest"
  imagePullPolicy: IfNotPresent
  rootUser: "minioadmin"
  rootPassword: "minioadminpassword"
  persistence:
    size: "10Gi"

palmr:
  api:
    enabled: true
    replicaCount: 1
    image: "kyantech/palmr-api:latest"
    imagePullPolicy: IfNotPresent
    port: 3000
  app:
    enabled: true
    replicaCount: 1
    image: "kyantech/palmr-app:latest"
    imagePullPolicy: IfNotPresent
    port: 80
    service:
      type: LoadBalancer
      port: 80
